mall/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'mall'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.homepage, name='home'),
    path('cart/', views.cart, name='cart'),
    path('send_email/', views.send_email, name='send_email'),
    path('purchased/', views.purchased, name='purchased'),
    path('received/', views.received, name='received'),
    path('management/', views.management, name='management'),
    path('add_commodity/', views.add_commodity, name='add_commodity'),
    path('modify_commodity/<int:cd_id>', views.modify_commodity, name='modify_commodity'),
    path('sales_statistics/', views.sales_statistics, name='sales_statistics'),
    path('user_statistics/', views.user_statistics, name='user_statistics')
]

shoppingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # my
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('mall.urls', 'mall'), namespace='mall')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# super user   : william shitman14@WXP
# regular user : wxp shitman14@WXP

users/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('register/', views.register, name='register'),
]

mall/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Commodity(models.Model):
    # 商品图片；名称；描述；价格；销量；上市日期
    photo = models.ImageField(upload_to='mall/images')
    name = models.CharField(max_length=50)
    description = models.TextField(default='物美价廉')
    price = models.FloatField(default=9)
    sales = models.PositiveIntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class MyCommodity(models.Model):
    # 购物车中商品的 数量；商品种类；拥有者；加入时间
    amount = models.PositiveIntegerField(default=1)
    goods = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.goods.name

    # 计算该商品的总价
    def total_cost(self):
        return self.amount * self.goods.price


class ReceivedCommodity(models.Model):
    # 购买日期；拥有者，名字，数量，价格，商品图片
    bought_date = models.DateTimeField(auto_now_add=True)
    # 每个用户有自己的订单查看
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # 注意：删除了 My Commodity 但是，收到的不会消失，所以不能用外键
    name = models.CharField(max_length=50)
    amount = models.PositiveIntegerField()
    price = models.FloatField()
    photo = models.ImageField(upload_to='mall/images')

    def __str__(self):
        return self.name

    # 计算总价
    def total_cost(self):
        return self.price * self.amount

mall/forms.py
from django import forms
from .models import Commodity


class CommodityForm(forms.ModelForm):
    class Meta:
        model = Commodity
        fields = '__all__'

mall/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.urls import reverse

from .models import Commodity, MyCommodity, ReceivedCommodity

from .forms import CommodityForm


# Create your views here.

def index(request):
    return render(request, 'mall/index.html')


def homepage(request):
    if request.method == 'POST':
        # 点击了 “加入购物车” 后的操作
        gid = request.POST['gid']  # 获取所加商品的 id
        # 获取所有的购物车商品
        mys = MyCommodity.objects.filter(owner=request.user).order_by('date_added')
        flag = 0
        # 遍历购物车商品
        for m in mys:
            # 若存在，商品数量加一
            if m.goods.id == eval(gid):
                m.amount += 1
                m.save()
                flag += 1
        # 不存在，新建 MyCommodity 实体存储该信息
        if flag == 0:
            new_my = MyCommodity(amount=1,
                                 goods=Commodity.objects.get(id=gid),
                                 owner=request.user)
            new_my.save()
    # 获取所有商品，后渲染
    goods = Commodity.objects.all()
    context = {'goods': goods}
    return render(request, 'mall/home.html', context)


@login_required()
def cart(request):
    """ 显示用户的购物车 """
    if request.method == 'POST':
        # 实现购物车商品的移除（数量减一）
        remove = request.POST['remove']
        my_id = request.POST['my_id']  # 获取移除的购物车商品 id
        if eval(remove) == 1:
            temp = MyCommodity.objects.get(id=my_id)
            # 数量为一，直接移除；否则减一
            if temp.amount == 1:
                temp.delete()
            else:
                temp.amount -= 1
                temp.save()
    # 获取所有购物车商品
    my_cart = MyCommodity.objects.filter(owner=request.user).order_by('date_added')
    context = {'my_cart': my_cart}
    return render(request, 'mall/cart.html', context)


@login_required()
def send_email(request):
    context = {}
    total_cost = 0
    if request.method == 'POST':
        buy_all = request.POST.get('buy_all')
        if buy_all and buy_all == 'yes':
            all_my = MyCommodity.objects.all()
            for a in all_my:
                total_cost += a.total_cost()
            context = {'all_my': all_my, 'total_cost': total_cost}

        else:
            my_id = request.POST['my_id']
            wanted = MyCommodity.objects.get(id=my_id)
            total_cost = wanted.total_cost()
            context = {'wanted': wanted, 'total_cost': total_cost}

    return render(request, 'mall/send_email.html', context)


@login_required()
def purchased(request):
    if request.method == 'POST':
        # 邮件内容清单
        text = '您所购买的宝贝清单：\n'
        email = request.POST['email']
        wanted_id = request.POST.get('wanted_id')
        if wanted_id:
            # 根据得到想要的商品信息
            wanted = MyCommodity.objects.get(id=wanted_id)
            text += f'{wanted.goods.name}   '
            text += f'数量:  {wanted.amount}    '
            text += f'总价:  ￥{wanted.total_cost()} \n'
            # 加入已购买的宝贝
            new_received = ReceivedCommodity(name=wanted.goods.name, amount=wanted.amount, price=wanted.goods.price,
                                             photo=wanted.goods.photo)
            new_received.owner = request.user
            new_received.save()
            # 给此商品加 销量
            com = Commodity.objects.get(id=wanted.goods.id)
            com.sales += wanted.amount
            com.save()
            # 从购物车移出此商品
            wanted.delete()

        else:
            all_buy = MyCommodity.objects.all()
            for a in all_buy:
                text += f'{a.goods.name}   '
                text += f'数量:  {a.amount}    '
                text += f'总价:  ￥{a.total_cost()} \n'

                # 给此商品 加 销量
                com = Commodity.objects.get(id=a.goods.id)
                com.sales += a.amount
                com.save()
                # 加入已购买的宝贝
                new_received = ReceivedCommodity(name=a.goods.name, amount=a.amount, price=a.goods.price,
                                                 photo=a.goods.photo)
                new_received.owner = request.user
                new_received.save()

            # 清除购物车
            MyCommodity.objects.all().delete()
        text += '欢迎下次使用，祝您生活愉快！！！' + '\n🎈🎈🎈✨✨✨'
        send_mail(
            subject='感谢使用WMall，您所购买的商品已送至门口，请及时取件',
            message=text,
            from_email='2396469068@qq.com',  # 用于发送的邮箱
            recipient_list=[fr'{email}'],  # 用户所输入的邮箱
            fail_silently=False
        )
    return render(request, 'mall/purchased.html')


@login_required()
def received(request):
    # 根据用户筛选已购买的商品
    all_received = ReceivedCommodity.objects.filter(owner=request.user).order_by('bought_date')
    context = {'all_received': all_received}
    return render(request, 'mall/received.html', context)


@login_required()
def management(request):
    if request.method == 'POST':
        modify = request.POST.get('modify')
        if modify:
            pass
        else:  # 删除商品
            cd_id = request.POST.get('cd_id')
            if cd_id:
                temp = Commodity.objects.get(id=cd_id)
                temp.delete()
    # 得到所有商品
    commodities = Commodity.objects.all()
    context = {'commodities': commodities}
    return render(request, 'mall/management.html', context)


@login_required()
def add_commodity(request):
    if request.method == 'POST':
        # 得到商品信息
        form = CommodityForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # 保存该商品并重定向到 商品管理页面
            return HttpResponseRedirect(reverse('mall:management'))
    else:
        # 不是 ‘POST’ 请求则提供表单以便获取信息
        form = CommodityForm()
    context = {'form': form}
    return render(request, 'mall/add_commodity.html', context)


@login_required()
def modify_commodity(request, cd_id):
    # 根据 id 得到所需修改的商品
    commodity = Commodity.objects.get(id=cd_id)
    if request.method == 'POST':
        # 得到修改后的信息
        form = CommodityForm(instance=commodity, data=request.POST)
        if form.is_valid():
            form.save()
            # 保存该商品的新信息并重定向到 商品管理页面
            return HttpResponseRedirect(reverse('mall:management'))
    else:
        # 提供表单以供修改
        form = CommodityForm(instance=commodity)
    context = {'form': form, 'commodity': commodity}
    return render(request, 'mall/modify_commodity.html', context)


@login_required()
def sales_statistics(request):
    all_received = ReceivedCommodity.objects.all()
    # 不同用户买的商品应该归类到一起
    all_sale = {}  # { ‘商品名字’，[商品价格，商品数量，商品总价]  }
    # 单价 ； 销量 ； 总价
    for a in all_received:
        if a.name in all_sale:
            all_sale[f'{a.name}'][0] = a.price  # 单价
            all_sale[f'{a.name}'][1] += a.amount  # 销量
            all_sale[f'{a.name}'][2] += a.price * a.amount  # 总价
        else:
            temp = {f'{a.name}': [a.price, a.amount, a.price * a.amount]}
            all_sale.update(temp)
    context = {'all_sale': all_sale}
    return render(request, 'mall/sales_statistics.html', context)


@login_required()
def user_statistics(request):
    # 订单记录
    received_c = ReceivedCommodity.objects.all().order_by('bought_date')
    indent = {}
    for r in received_c:
        if r.owner.email:
            continue  # 忽略管理员用户
        elif r.owner in indent:
            # 已经有此用户，加一列购买记录
            indent[r.owner].append([r.owner.username, r.name, r.price, r.amount, r.total_cost(), r.bought_date])
        else:
            temp = {r.owner: [[r.owner.username, r.name, r.price, r.amount, r.total_cost(), r.bought_date]]}
            indent.update(temp)
    # 购物车记录
    my_c = MyCommodity.objects.all().order_by('date_added')
    cart_record = {}
    for m in my_c:
        if m.owner.email:
            continue
        elif m.owner in cart_record:
            cart_record[m.owner].append(
                [m.owner.username, m.goods.name, m.goods.price, m.amount, m.total_cost(), m.date_added])
        else:
            temp = {m.owner: [[m.owner.username, m.goods.name, m.goods.price, m.amount, m.total_cost(), m.date_added]]}
            cart_record.update(temp)

    context = {'indent': indent, 'cart_record': cart_record}
    return render(request, 'mall/user_statistics.html', context)

mall/templates/mall/add_commodity.html
{% extends 'mall/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <br><h4>添加一个新的商品</h4><hr>
{% endblock %}

{% block content %}
    <form action="{% url 'mall:add_commodity' %}" method="post"  class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn-lg btn-block btn btn-outline-success">添加</button>
    </form>
{% endblock %}

mall/templates/mall/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>WMall</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light" width="100%" style="background-color: mintcream">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mall:index' %}">WMall</a>

        {#        缩小后隐藏的按钮 #}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {#        根据窗口大小隐藏的按钮 #}
        <div class="collapse navbar-collapse" id="navbarScroll">
            {#          蠢方法解决了 navbar-right 没有效果的失误。。#}
            <div class="nav navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mall:home' %}">首页</a>
                </li>
            </div>

            {#            导航条右侧, 登陆注册以及状态判断#}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">欢迎, {{ user.username }}！</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mall:cart' %}">购物车</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mall:received' %}">已买到的宝贝</a>
                    </li>

                    {% if user.email %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-expanded="false">
                                管理员中心
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'mall:management' %}">商品管理</a>
                                <a class="dropdown-item" href="{% url 'mall:sales_statistics' %}">销售统计</a>
                                <a class="dropdown-item" href="{% url 'mall:user_statistics' %}">客户日志</a>
                            </div>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">注销</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container -->


</body>

mall/templates/mall/cart.html
{% extends 'mall/base.html' %}
{% load bootstrap4 %}


{% block header %}
    <br><h3>{{ user.username }} 的购物车</h3>
    <hr>

    {% if my_cart %}
        <div class="row" style="margin: 0">
            <div class="col-2 text-left">
                图片展示
            </div>
            <div class="col-2 text-left" style="margin-left: 0">
                商品名称
            </div>
            <div class="col-2">
                单价
            </div>

            <div class="col-2">
                数量
            </div>
            <div class="col-2">
                金额
            </div>
            <div class="col-2 text-center">
                操作
            </div>
        </div>
    {% endif %}

    <br>

{% endblock header %}


{% block content %}
    {% for my in my_cart %}
        <div class="row">

            <div class="card mb-3" style="max-height: 100px; width: 100%;">
                <div class="row">
                    <div class="col-md-2">
                        <div style="overflow: hidden;">
                            <div class="zoomImage img-thumbnail"
                                 style="
                                         background-image:url('/media/{{ my.goods.photo }}');
                                         width: 100px;
                                         height: 100px;
                                         {#padding-bottom: 100%;#}
                                         overflow: hidden;
                                         background-position: center center;
                                         background-repeat: no-repeat;
                                         -webkit-background-size: cover;
                                         -moz-background-size: cover;
                                         background-size: cover;"></div>
                        </div>
                    </div>
                    <div class="col-2">
                        <span style="line-height: 100px">&nbsp;&nbsp; {{ my.goods.name }}</span>
                    </div>
                    <div class="col-md-2">
                        <span class="text"
                              style="line-height: 100px; color: coral;"> <strong><small>￥:</small> {{ my.goods.price|floatformat }}</strong></span>
                    </div>
                    <div class="col-md-2">
                        <span style="line-height: 100px">{{ my.amount }}</span>
                    </div>
                    <div class="col-md-2">
                        <span class="text"
                              style="line-height: 100px; color: coral"> <strong><small>￥:</small> {{ my.total_cost|floatformat }}</strong></span>
                    </div>
                    <div class="col-2 text-center" style="display: flex; justify-content: center;align-items: center;">

                        <form action="{% url 'mall:cart' %}" method="post" style="margin: 0;">
                            {% csrf_token %}
                            <input name="remove" type="hidden" value="1">
                            <input name="my_id" type="hidden" value="{{ my.id }}">
                            &nbsp;
                            <button type="submit" class="btn btn-sm btn-outline-success">
                                移除
                            </button>
                        </form>
                        &nbsp;
                        <form action="{% url 'mall:send_email' %}" method="post" style="margin: 0;">
                            {% csrf_token %}
                            <input name="my_id" type="hidden" value="{{ my.id }}">
                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                购买
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% empty %}

        <div class="jumbotron">
            <h1 class="display-4">😀😀😀 <br> 这里空空如也。。。</h1>
            <p class="lead">
                快去选购心仪的商品吧</p>
            <hr class="my-4">
            <a class="btn btn-outline-success btn-lg" href="{% url 'mall:home' %}" role="button">返回首页</a>
        </div>


    {% endfor %}

    <hr>

    {#    移除所有商品，有时间的话可以选择实现一下 #}
    {#    <form action="{% url 'mall:cart' %}" method="post" style="margin: 0;">#}
    {#        {% csrf_token %}#}
    {#        <input name="remove" type="hidden" value="1">#}
    {#        <input name="my_id" type="hidden" value="{{ my.id }}">#}
    {#        &nbsp;#}
    {#        <button type="submit" class="btn btn-sm btn-outline-success">#}
    {#            移除#}
    {#        </button>#}
    {#    </form>#}

    {% if my_cart %}
        <form method="post" action="{% url 'mall:send_email' %}">
            {% csrf_token %}
            <input name="buy_all" value="yes" type="hidden">
            <button type="submit" class="btn-lg btn-block btn btn-outline-danger">结算所有</button>
        </form>
    {% endif %}


{% endblock content %}

mall/templates/mall/home.html
{% extends 'mall/base.html' %}

{% block header %}

{% endblock header %}


{% block content %}
    <div class="row">
        {% for good in goods %}

            <div class="col-md-2">
                <br>
                <div class="zoomImage img-thumbnail"
                     style="
                             background-image:url('../../../media/{{ good.photo }}');
                             width: 100%;
                             height: 155px;
                             {#padding-bottom: 100%;#}
                             overflow: hidden;
                             background-position: center center;
                             background-repeat: no-repeat;
                             -webkit-background-size: cover;
                             -moz-background-size: cover;
                             background-size: cover;"></div>
                <div class="card" style="overflow: hidden">
                    {#                    <div class="row" style="overflow: hidden; height: 200px;width: auto">#}
                    {#                        <img src="../../../media/{{ good.photo }}" class="card-img-top" alt="...">#}
                    {#                    </div>#}

                    <p class="text-left" style="margin: 0">
                        &nbsp;&nbsp; {{ good.name }}
                    </p>
                    <p class="text-left" style="color: coral;margin: 0">
                        &nbsp;&nbsp; <strong><small>￥：</small> {{ good.price }}</strong>
                    </p>
{#                    <a href="{{ good.id }}">#}
{#                        <button type="button" class="btn btn-light btn-block btn-sm">#}
{#                            查看详情#}
{#                        </button>#}
{#                    </a>#}
                    {% if user.is_authenticated %}
                        <form action="{% url 'mall:home' %}" method="post" style="margin: 0;">
                        {% csrf_token %}
                        <input name="gid" type="hidden" value="{{ good.id }}">
                        <button type="submit" class="btn btn-light btn-block btn-sm">
                                加入购物车
                            </button>
                        </form>
                    {% endif %}


                </div>
                <br>
            </div>
        {% empty %}
            <p>no commodity have been added yet.</p>
        {% endfor %}
    </div>
{% endblock content %}

<body>
shit here
</body>

mall/templates/mall/index.html
{% extends 'mall/base.html' %}

{% block content %}
    <br>
    <div class="jumbotron">
        <h1 class="display-4">你好!</h1>
        <p class="lead">这是一个小型电子商务网站</p>
        <hr class="my-4">
        <p>created by william</p>
        <a class="btn btn-primary btn-lg" href="{% url 'mall:home' %}" role="button">进入首页</a>
    </div>
{% endblock %}

mall/templates/mall/management.html
{% extends 'mall/base.html' %}

{% block header %}
    <div class="row">
        <div class="col-md-10">
            <br><h4>管理&nbsp; WMall&nbsp;的商品</h4>
        </div>

        <div class="col-md-2" style="display: flex; justify-content: end;align-items: end;">
            <a href="{% url 'mall:add_commodity' %}">
                <button type="button" class="btn btn-block btn-outline-info">添加商品</button>
            </a>
        </div>
    </div>
    <hr>

    {% if commodities %}
        <div class="row" style="margin: 0">
            <div class="col-2 text-left">
                图片展示
            </div>
            <div class="col-2 text-left" style="margin-left: 0">
                商品名称
            </div>
            <div class="col-2">
                单价
            </div>

            <div class="col-3">
                上市日期
            </div>
            <div class="col-3 text-center">
                操作
            </div>
        </div>
    {% endif %}

    <br>
{% endblock header %}

{% block content %}
    {% for commodity in commodities %}
        <div class="row">

            <div class="card mb-3" style="max-height: 100px; width: 100%;">
                <div class="row">
                    <div class="col-md-2">
                        <div style="overflow: hidden;">
                            <div class="zoomImage img-thumbnail"
                                 style="
                                         background-image:url('/media/{{ commodity.photo }}');
                                         width: 100px;
                                         height: 100px;
                                         {#padding-bottom: 100%;#}
                                         overflow: hidden;
                                         background-position: center center;
                                         background-repeat: no-repeat;
                                         -webkit-background-size: cover;
                                         -moz-background-size: cover;
                                         background-size: cover;"></div>
                        </div>
                    </div>
                    <div class="col-2">
                        <span style="line-height: 100px">&nbsp;&nbsp; {{ commodity.name }}</span>
                    </div>
                    <div class="col-md-2">
                        <span class="text"
                              style="line-height: 100px; color: coral;"> <strong><small>￥:</small> {{ commodity.price|floatformat }}</strong></span>
                    </div>
                    <div class="col-md-3">
                        <span class="text"
                              style="line-height: 100px;">{{ commodity.date_added|date:'Y-m-d H:i:s' }}</span>
                    </div>
                    <div class="col-3 text-center" style="display: flex; justify-content: center;align-items: center;">
{#                        <form action="{% url 'mall:modify_commodity' commodity.id %}" method="post" style="margin: 0;">#}
{#                            {% csrf_token %}#}
{#                            <input name="modify" type="hidden" value="yes">#}
{#                            <input name="cd_id" type="hidden" value="{{ commodity.id }}">#}
{#                            &nbsp;#}
{#                            <button type="submit" class="btn btn-outline-success">#}
{#                                修改#}
{#                            </button>#}
{#                        </form>#}
                        <a href="{% url 'mall:modify_commodity' commodity.id %}">
                            <button type="button" class="btn btn-outline-success">
                                修改
                            </button>
                        </a>
                        &nbsp;
                        <form action="{% url 'mall:management' %}" method="post" style="margin: 0;">
                            {% csrf_token %}
                            <input name="cd_id" type="hidden" value="{{ commodity.id }}">
                            <button type="submit" class="btn btn-outline-danger">
                                删除
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% empty %}
         <div class="jumbotron">
            <h1 class="display-4">😀😀😀 <br> 这里空空如也。。。</h1>
            <p class="lead">
                快添加商品让 WMall 运作起来吧！</p>
            <hr class="my-4">
            <a class="btn btn-outline-success btn-lg" href="{% url 'mall:add_commodity' %}" role="button">添加商品</a>
        </div>


    {% endfor %}
{% endblock content %}

mall/templates/mall/modify_commodity.html
{% extends 'mall/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <br><h4>修改 {{ commodity.name }} 的相关属性</h4><hr>
{% endblock %}

{% block content %}
    <form action="{% url 'mall:modify_commodity' commodity.id %}" method="post"  class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn-lg btn-block btn btn-outline-success">确认修改</button>
    </form>
{% endblock %}

mall/templates/mall/purchased.html
{% extends 'mall/base.html' %}

{% block header %}

{% endblock header %}


{% block content %}
    <br>
    <div class="jumbotron">
        <h1 class="display-4">下单成功!</h1>
        <p class="lead">商品将在24小时内尽早发货<br>
                        请留意您的邮箱以获取及时的物流信息</p>
        <hr class="my-4">
{#        <p>created by william</p>#}
        <a class="btn btn-outline-success btn-lg" href="{% url 'mall:home' %}" role="button">返回首页</a>
    </div>
{% endblock content %}

mall/templates/mall/sales_statistics.html
{% extends 'mall/base.html' %}

{% block header %}
    <br><h3>销售统计报表</h3>
    <hr>
{% endblock %}


{% block content %}


    <table class="table" style="width: 100%">
        <thead>
        <tr>
            {#            <th scope="col">编号</th>#}
            <th scope="col">商品名</th>
            <th scope="col">单价</th>
            <th scope="col">销售量</th>
            <th scope="col">销售总额</th>
        </tr>
        </thead>

        <tbody>

        {% for name, info in all_sale.items %}
            <tr>
                {#                <th scope="row">1</th>#}
                <td>{{ name }}</td>
                <td>{{ info.0|floatformat }}</td>
                <td>{{ info.1 }}</td>
                <td>{{ info.2|floatformat }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}