mall/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'mall'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.homepage, name='home'),
    path('cart/', views.cart, name='cart'),
    path('send_email/', views.send_email, name='send_email'),
    path('purchased/', views.purchased, name='purchased'),
    path('received/', views.received, name='received'),
    path('management/', views.management, name='management'),
    path('add_commodity/', views.add_commodity, name='add_commodity'),
    path('modify_commodity/<int:cd_id>', views.modify_commodity, name='modify_commodity'),
    path('sales_statistics/', views.sales_statistics, name='sales_statistics'),
    path('user_statistics/', views.user_statistics, name='user_statistics')
]

shoppingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # my
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('mall.urls', 'mall'), namespace='mall')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# super user   : william shitman14@WXP
# regular user : wxp shitman14@WXP

users/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('register/', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    # 如果不是 POST 请求，生成内置表单 UserCreationForm
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # 使用内置表单 UserCreationForm 得到注册信息
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            # 保存新用户信息，并授权登录
            new_user = form.save()
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            # 登录后重定向至商品主页
            return HttpResponseRedirect(reverse('mall:home'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/users/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<body>
<nav class="navbar navbar-expand-lg navbar-light" width="100%" style="background-color: mintcream">
    <div class="container">
        <a class="navbar-brand" href="{% url 'users:index' %}">WMall</a>
        {#        缩小后隐藏的按钮 #}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {#        根据窗口大小隐藏的按钮 #}
        <div class="collapse navbar-collapse" id="navbarScroll">
            {#          蠢方法解决了 navbar-right 没有效果的失误。。#}
            <div class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            <span class="navbar-text">
                it's a mall selling dream and goods
            </span>
            </div>

            {#            导航条右侧, 登陆注册以及状态判断#}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link">Hello, {{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">register</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>

</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container -->
</body>

templates/users/login.html
{% extends 'users/base.html' %}
{% load bootstrap4 %}

{% block header %}
        <br>

    <h2>Log in to your account</h2><hr>
{% endblock header %}


{% block content %}
    <br>
    {% if form.errors %}
        <p>shit</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="login" class="btn btn-outline-primary">log in</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'users:index' %}"/>
    </form>
{% endblock content %}